"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import styles from "@/app/styles/table.module.css";
type Supplier={ID:number;Ad:string;Yetkili:string;Telefon:string;Email:string;Adres:string;VergiDairesi:string;VergiNo:string;Durum:string};
const blank={ID:0,Ad:"",Yetkili:"",Telefon:"",Email:"",Adres:"",VergiDairesi:"",VergiNo:"",Durum:"Aktif"};
export default function TedarikciClient(){
  const [rows,setRows]=useState<Supplier[]>([]),[search,setSearch]=useState(""),[form,setForm]=useState<Supplier|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{const r=await fetch(`/api/kys/tedarikciler?all=1&search=${encodeURIComponent(search)}`);const j=await r.json();if(!r.ok)throw new Error(j.error);setRows(j.data||[]);}catch(e){setError(e instanceof Error?e.message:"Liste alınamadı.");}},[search]);
  useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t);},[load]);
  async function save(){setBusy(true);setError("");try{const r=await fetch("/api/kys/tedarikciler",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await r.json();if(!r.ok)throw new Error(j.error);setForm(null);await load();}catch(e){setError(e instanceof Error?e.message:"Kaydedilemedi.");}finally{setBusy(false);}}
  async function remove(row:Supplier){if(!confirm(`${row.Ad} tedarikçisini listeden çıkarmak istiyor musunuz? Geçmiş satın alma kayıtları korunur.`))return;setBusy(true);try{const r=await fetch(`/api/kys/tedarikciler?id=${row.ID}`,{method:"DELETE"});const j=await r.json();if(!r.ok)throw new Error(j.error);await load();}catch(e){setError(e instanceof Error?e.message:"Silinemedi.");}finally{setBusy(false);}}
  return <div className={styles.page} style={{maxWidth:"none"}}><h1 className={styles.pageTitle}>Tedarikçi Listesi</h1><p>Satın alma yapılan firmalar ve iletişim bilgileri. Listeden çıkarılan firmaların geçmiş kayıtları korunur.</p>
    {error&&<p role="alert" className={styles.errorBanner}>{error}</p>}
    <div className={styles.toolbar}><input className={styles.searchInput} aria-label="Tedarikçi ara" placeholder="Firma, yetkili veya vergi no ara…" value={search} onChange={e=>setSearch(e.target.value)}/><Link className={styles.cancelBtn} href="/laboratuvar/kys/talep-listesi">Talep listesi</Link><button className={styles.addBtn} onClick={()=>setForm({...blank})}>+ Tedarikçi ekle</button></div>
    <div className={styles.tableCard}><div className={styles.tableWrapper}><table className={styles.table}><thead><tr><th>Firma</th><th>Yetkili</th><th>Telefon</th><th>E-posta</th><th>Vergi No</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.ID}><td>{r.Ad}</td><td>{r.Yetkili||"—"}</td><td>{r.Telefon||"—"}</td><td>{r.Email||"—"}</td><td>{r.VergiNo||"—"}</td><td>{r.Durum}</td><td><button className={styles.editBtn} onClick={()=>setForm({...r})}>Düzenle</button>{r.Durum==="Aktif"&&<button disabled={busy} className={styles.cancelBtn} onClick={()=>remove(r)}>Listeden çıkar</button>}</td></tr>):<tr><td colSpan={7}>Tedarikçi bulunamadı.</td></tr>}</tbody></table></div></div>
    {form&&<div className={styles.modalOverlay}><div className={styles.modal} role="dialog" aria-modal="true" aria-label="Tedarikçi bilgileri"><div className={styles.modalHeader}><h2>Tedarikçi bilgileri</h2><button disabled={busy} onClick={()=>setForm(null)}>×</button></div><div className={styles.modalBody}><div className={styles.formGrid}>{([["Ad","Firma adı *"],["Yetkili","Yetkili"],["Telefon","Telefon"],["Email","E-posta"],["VergiDairesi","Vergi dairesi"],["VergiNo","Vergi no"],["Adres","Adres"]] as const).map(([k,label])=><div className={styles.formGroup} key={k}><label>{label}<input disabled={busy} value={form[k]||""} onChange={e=>setForm(f=>f?{...f,[k]:e.target.value}:f)}/></label></div>)}<div className={styles.formGroup}><label>Durum<select disabled={busy} value={form.Durum} onChange={e=>setForm(f=>f?{...f,Durum:e.target.value}:f)}><option>Aktif</option><option>Pasif</option></select></label></div></div></div><div className={styles.modalFooter}><button disabled={busy} onClick={()=>setForm(null)}>Vazgeç</button><button className={styles.saveBtn} disabled={busy||!form.Ad.trim()} onClick={save}>{busy?"Kaydediliyor…":"Kaydet"}</button></div></div></div>}
  </div>;
}
