"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Eye, Paperclip, RefreshCw, Send } from "lucide-react";
import { requestStatuses, type CustomerRequest, type RequestMessage } from "@/lib/customerRequestTypes";
import table from "@/app/styles/table.module.css";
import styles from "./requests.module.css";
const sourceName = (source: string) => source === "spektrotek" ? "Spektrotek" : "Unique Analyse";
const date = (value: string) => new Date(value).toLocaleString("tr-TR");
async function api(path: string, options?: RequestInit) {
  const response = await fetch(`/api/musteri-talepleri${path}`, { cache: "no-store", ...options });
  const data = await response.json(); if (!response.ok) throw new Error(data.error || "İşlem tamamlanamadı."); return data;
}
export default function CustomerRequestsClient({ number }: { number?: string }) {
  const [items, setItems] = useState<CustomerRequest[]>([]);
  const [detail, setDetail] = useState<{ request: CustomerRequest; messages: RequestMessage[] } | null>(null);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [search, setSearch] = useState(""); const [source, setSource] = useState(""); const [status, setStatus] = useState("");
  const [text, setText] = useState(""); const [files, setFiles] = useState<File[]>([]); const [fileKey, setFileKey] = useState(0); const [link, setLink] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const data = await api(number ? `/${number}` : ""); if (number) setDetail(data); else setItems(data); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }, [number]);
  useEffect(() => { void load(); }, [load]);
  async function action(work: () => Promise<void>) { setBusy(true); setError(""); setNotice(""); try { await work(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  const filtered = items.filter(item => (!source || item.source === source) && (!status || item.status === status) && `${item.number} ${item.company} ${item.subject} ${item.type}`.toLocaleLowerCase("tr-TR").includes(search.toLocaleLowerCase("tr-TR")));
  const request = detail?.request;
  return <div className={`${table.page} ${styles.page}`}>
    <div className={table.pageHeader}><div>{number && <Link href="/iletisim/musteri-talep" className={styles.back}><ArrowLeft size={16} /> Taleplere dön</Link>}<h1 className={table.pageTitle}>{number ? `Talep #${number}` : "Müşteri Talep"}</h1><p className={table.pageSubtitle}>{number ? "Talep bilgileri ve müşteri yazışmaları" : "Spektrotek ve Unique Analyse web sitelerinden gelen talepler"}</p></div><button className={styles.button} onClick={() => void load()} disabled={loading || busy}><RefreshCw size={16} /> Yenile</button></div>
    {error && <div role="alert" className={styles.error}>{error}</div>}{notice && <div role="status">{notice}</div>}
    {loading ? <p role="status">Talepler yükleniyor…</p> : !number ? <>
      <div className={styles.filters}><input aria-label="Talep ara" placeholder="Firma, talep no, konu veya tür ara…" value={search} onChange={e => setSearch(e.target.value)} /><select aria-label="Kaynak" value={source} onChange={e => setSource(e.target.value)}><option value="">Tüm kaynaklar</option><option value="spektrotek">Spektrotek</option><option value="uniqueanalyse">Unique Analyse</option></select><select aria-label="Durum" value={status} onChange={e => setStatus(e.target.value)}><option value="">Tüm durumlar</option>{requestStatuses.map(s => <option key={s}>{s}</option>)}</select><span>{filtered.length} talep</span></div>
      <div className={styles.tableWrap}><table className={styles.table}><thead><tr>{["Kaynak", "Talep Türü", "Talep Tarihi", "Talep No", "Firma", "Durum", "Detay"].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{filtered.map(item => <tr key={item.number}><td>{sourceName(item.source)}</td><td>{item.type}</td><td>{date(item.createdAt)}</td><td className={styles.number}>{item.number}</td><td>{item.company}</td><td><span className={styles.badge} data-status={item.status}>{item.status}</span></td><td><Link className={styles.icon} aria-label={`${item.number} numaralı talebin detayını aç`} href={`/iletisim/musteri-talep/${item.number}`}><Eye size={18} /></Link></td></tr>)}{!filtered.length && <tr><td colSpan={7} className={styles.empty}>{items.length ? "Filtrelere uygun talep bulunamadı." : "Henüz talep bulunmuyor. Web sitelerinden gönderilen talepler burada listelenecek."}</td></tr>}</tbody></table></div>
    </> : request && <>
      <section className={styles.panel}><div className={styles.panelHead}><h2>Talep bilgileri</h2><select aria-label="Talep durumu" value={request.status} disabled={busy} onChange={e => { const value = e.target.value; void action(async () => { await api(`/${number}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: value }) }); await load(); }); }}>{requestStatuses.map(s => <option key={s}>{s}</option>)}</select></div><dl className={styles.fields}>{[["Kaynak", sourceName(request.source)], ["Talep türü", request.type], ["Talebi oluşturan firma", request.company], ["Yetkili adı", request.name], ["E-posta", request.email], ["Telefon", request.phone], ["Talep tarihi", date(request.createdAt)], ["Konu başlığı", request.subject]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><h3>Konu detayı</h3><p className={styles.body}>{request.body}</p></section>
      <section className={styles.panel}><div className={styles.panelHead}><h2>Yazışmalar</h2><span>{detail.messages.length} mesaj</span></div>{!detail.messages.length && <p className={styles.muted}>Henüz yanıt gönderilmedi.</p>}{detail.messages.map(message => <article className={styles.message} key={message.id} data-role={message.role}><header><strong>{message.role === "staff" ? "Portal yanıtı" : request.name}</strong><time dateTime={message.createdAt}>{date(message.createdAt)}</time></header><p className={styles.body}>{message.text}</p>{message.files.map((file, index) => <a key={index} className={styles.attachment} href={`/api/musteri-talepleri/${number}/files/${message.id}/${index}`}><Paperclip size={14} />{file.name} ({Math.ceil(file.size / 1024)} KB)</a>)}</article>)}
      <form className={styles.composer} onSubmit={e => { e.preventDefault(); void action(async () => { const form = new FormData(); form.set("text", text); files.forEach(file => form.append("files", file)); await api(`/${number}/messages`, { method: "POST", body: form }); setText(""); setFiles([]); setFileKey(key => key + 1); await load(); setNotice("Yanıt kaydedildi. Müşteri takip sayfasında görünecek."); }); }}><label htmlFor="reply">Müşteriye yanıt</label><textarea id="reply" maxLength={20000} rows={5} value={text} onChange={e => setText(e.target.value)} placeholder="Yanıtınızı yazın…" disabled={busy} /><label htmlFor="request-files">Dosya ekle (en fazla 3 dosya, her biri 2 MB)</label><input key={fileKey} id="request-files" type="file" multiple accept=".pdf,.docx,.xlsx,.png,.jpg,.jpeg,.txt,.csv" disabled={busy} onChange={e => setFiles(Array.from(e.target.files || []))} /><button className={styles.primary} disabled={busy || (!text.trim() && !files.length)}><Send size={16} />{busy ? "Gönderiliyor…" : "Yanıtı gönder"}</button></form></section>
      <section className={styles.panel}><h2>Müşteri takip bağlantısı</h2><p className={styles.muted}>Bağlantı 180 gün geçerlidir. Yenisi oluşturulursa önceki bağlantı geçersiz olur. Web sitesindeki takip sayfası entegrasyon tamamlandığında kullanılabilir.</p><button className={styles.button} disabled={busy} onClick={() => void action(async () => { const result = await api(`/${number}/tracking-link`, { method: "POST" }); setLink(result.trackingUrl); })}>Yeni takip bağlantısı oluştur</button>{link && <div className={styles.linkRow}><input aria-label="Müşteri takip bağlantısı" readOnly value={link} /><button className={styles.button} onClick={() => void action(async () => { await navigator.clipboard.writeText(link); setNotice("Bağlantı kopyalandı."); })}>Kopyala</button></div>}</section>
    </>}
  </div>;
}
